const defaultProperties = [
  {
    legacyId: '1',
    title: 'Modern Penthouse with Skyline Views',
    location: 'Mumbai, Maharashtra',
    price: 4500000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3500,
    yearBuilt: 2022,
    featured: true,
    description:
      'Stunning penthouse located in the heart of Manhattan with breathtaking skyline views. Features floor-to-ceiling windows, state-of-the-art kitchen, and a private terrace.',
    amenities: ['Rooftop Terrace', 'Wine Cellar', 'Home Theater', 'Spa', 'Private Elevator'],
    image: '/properties/penthouse-3.jpg',
    images: ['/properties/penthouse-3.jpg'],
    videos: [],
    media: [{ type: 'image', url: '/properties/penthouse-3.jpg' }],
  },
  {
    legacyId: '2',
    title: 'Beachfront Villa with Pool',
    location: 'Goa',
    price: 3200000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4200,
    yearBuilt: 2020,
    featured: true,
    description:
      'Luxury beachfront villa with direct beach access. Includes Olympic-size swimming pool, smart home system, and panoramic ocean views.',
    amenities: ['Private Beach', 'Pool', 'Gym', 'Sauna', 'Guest House'],
    image: '/properties/beachfront-7.jpg',
    images: ['/properties/beachfront-7.jpg'],
    videos: [],
    media: [{ type: 'image', url: '/properties/beachfront-7.jpg' }],
  },
  {
    legacyId: '3',
    title: 'Contemporary Downtown Loft',
    location: 'Bangalore, Karnataka',
    price: 2800000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2800,
    yearBuilt: 2019,
    featured: true,
    description:
      'Spacious downtown loft in a historic building with modern amenities. Industrial-style architecture with luxury finishes.',
    amenities: ['Rooftop Access', 'Concierge', 'Fitness Center', 'Parking'],
    image: '/properties/mansion-1.jpg',
    images: ['/properties/mansion-1.jpg'],
    videos: [],
    media: [{ type: 'image', url: '/properties/mansion-1.jpg' }],
  },
  {
    legacyId: '4',
    title: 'Historic Estate with Gardens',
    location: 'Delhi NCR',
    price: 5100000,
    bedrooms: 6,
    bathrooms: 5,
    area: 5500,
    yearBuilt: 1995,
    featured: true,
    description:
      'Magnificent historic estate set on 2 acres of manicured gardens. Features original architectural details combined with modern luxuries.',
    amenities: ['Tennis Court', 'Gardens', 'Staff Quarters', 'Wine Cellar', 'Library'],
    image: '/properties/countryside-8.jpg',
    images: ['/properties/countryside-8.jpg'],
    videos: [],
    media: [{ type: 'image', url: '/properties/countryside-8.jpg' }],
  },
  {
    legacyId: '5',
    title: 'Luxury High-Rise Condo',
    location: 'Chennai, Tamil Nadu',
    price: 2100000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2500,
    yearBuilt: 2021,
    featured: false,
    description: 'Elegant high-rise condo with 360-degree views of Lake Michigan and downtown Chicago.',
    amenities: ['Concierge', 'Spa', 'Gym', 'Pool'],
    image: '/properties/estate-4.jpg',
    images: ['/properties/estate-4.jpg'],
    videos: [],
    media: [{ type: 'image', url: '/properties/estate-4.jpg' }],
  },
  {
    legacyId: '6',
    title: 'Modern Minimalist Home',
    location: 'Pune, Maharashtra',
    price: 3500000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3800,
    yearBuilt: 2023,
    featured: false,
    description: 'Contemporary minimalist home with clean lines and sustainable features throughout.',
    amenities: ['Solar Panels', 'Smart Home', 'Infinity Pool', 'Home Office'],
    image: '/properties/villa-2.jpg',
    images: ['/properties/villa-2.jpg'],
    videos: [],
    media: [{ type: 'image', url: '/properties/villa-2.jpg' }],
  },
  {
    legacyId: '7',
    title: 'Waterfront Mansion',
    location: 'Kolkata, West Bengal',
    price: 6800000,
    bedrooms: 7,
    bathrooms: 6,
    area: 6200,
    yearBuilt: 1998,
    featured: false,
    description: 'Prestigious waterfront mansion with private dock and breathtaking river views.',
    amenities: ['Private Dock', 'Boat Lift', 'Guest House', 'Home Theater'],
    image: '/properties/mansion-5.jpg',
    images: ['/properties/mansion-5.jpg'],
    videos: [],
    media: [{ type: 'image', url: '/properties/mansion-5.jpg' }],
  },
  {
    legacyId: '8',
    title: 'Desert Luxury Retreat',
    location: 'Ahmedabad, Gujarat',
    price: 2400000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    yearBuilt: 2022,
    featured: false,
    description: 'Exclusive desert retreat with resort-style amenities and stunning sunset views.',
    amenities: ['Resort Pool', 'Spa', 'Gym', 'Meditation Garden'],
    image: '/properties/townhouse-6.jpg',
    images: ['/properties/townhouse-6.jpg'],
    videos: [],
    media: [{ type: 'image', url: '/properties/townhouse-6.jpg' }],
  },
]

module.exports = defaultProperties