export interface Property {
  id: string
  title: string
  location: string
  price: number
  image: string
  bedrooms: number
  bathrooms: number
  area: number
  featured?: boolean
  description?: string
  amenities?: string[]
  images?: string[]
  yearBuilt?: number
}

export const properties: Property[] = [
  {
    id: '1',
    title: 'Modern Penthouse with Skyline Views',
    location: 'Mumbai, Maharashtra',
    price: 4500000,
    image: '/properties/penthouse-3.jpg',
    bedrooms: 4,
    bathrooms: 3,
    area: 3500,
    featured: true,
    description:
      'Stunning penthouse located in the heart of Manhattan with breathtaking skyline views. Features floor-to-ceiling windows, state-of-the-art kitchen, and a private terrace.',
    amenities: ['Rooftop Terrace', 'Wine Cellar', 'Home Theater', 'Spa', 'Private Elevator'],
    images: ['/properties/penthouse-3.jpg'],
    yearBuilt: 2022,
  },
  {
    id: '2',
    title: 'Beachfront Villa with Pool',
    location: 'Goa',
    price: 3200000,
    image: '/properties/beachfront-7.jpg',
    bedrooms: 5,
    bathrooms: 4,
    area: 4200,
    featured: true,
    description:
      'Luxury beachfront villa with direct beach access. Includes Olympic-size swimming pool, smart home system, and panoramic ocean views.',
    amenities: ['Private Beach', 'Pool', 'Gym', 'Sauna', 'Guest House'],
    images: ['/properties/beachfront-7.jpg'],
    yearBuilt: 2020,
  },
  {
    id: '3',
    title: 'Contemporary Downtown Loft',
    location: 'Bangalore, Karnataka',
    price: 2800000,
    image: '/properties/mansion-1.jpg',
    bedrooms: 3,
    bathrooms: 2,
    area: 2800,
    featured: true,
    description:
      'Spacious downtown loft in a historic building with modern amenities. Industrial-style architecture with luxury finishes.',
    amenities: ['Rooftop Access', 'Concierge', 'Fitness Center', 'Parking'],
    images: ['/properties/mansion-1.jpg'],
    yearBuilt: 2019,
  },
  {
    id: '4',
    title: 'Historic Estate with Gardens',
    location: 'Delhi NCR',
    price: 5100000,
    image: '/properties/countryside-8.jpg',
    bedrooms: 6,
    bathrooms: 5,
    area: 5500,
    featured: true,
    description:
      'Magnificent historic estate set on 2 acres of manicured gardens. Features original architectural details combined with modern luxuries.',
    amenities: ['Tennis Court', 'Gardens', 'Staff Quarters', 'Wine Cellar', 'Library'],
    images: ['/properties/countryside-8.jpg'],
    yearBuilt: 1995,
  },
  {
    id: '5',
    title: 'Luxury High-Rise Condo',
    location: 'Chennai, Tamil Nadu',
    price: 2100000,
    image: '/properties/estate-4.jpg',
    bedrooms: 3,
    bathrooms: 3,
    area: 2500,
    featured: false,
    description: 'Elegant high-rise condo with 360-degree views of Lake Michigan and downtown Chicago.',
    amenities: ['Concierge', 'Spa', 'Gym', 'Pool'],
    images: ['/properties/estate-4.jpg'],
    yearBuilt: 2021,
  },
  {
    id: '6',
    title: 'Modern Minimalist Home',
    location: 'Pune, Maharashtra',
    price: 3500000,
    image: '/properties/villa-2.jpg',
    bedrooms: 4,
    bathrooms: 4,
    area: 3800,
    featured: false,
    description: 'Contemporary minimalist home with clean lines and sustainable features throughout.',
    amenities: ['Solar Panels', 'Smart Home', 'Infinity Pool', 'Home Office'],
    images: ['/properties/villa-2.jpg'],
    yearBuilt: 2023,
  },
  {
    id: '7',
    title: 'Waterfront Mansion',
    location: 'Kolkata, West Bengal',
    price: 6800000,
    image: '/properties/mansion-5.jpg',
    bedrooms: 7,
    bathrooms: 6,
    area: 6200,
    featured: false,
    description: 'Prestigious waterfront mansion with private dock and breathtaking river views.',
    amenities: ['Private Dock', 'Boat Lift', 'Guest House', 'Home Theater'],
    images: ['/properties/mansion-5.jpg'],
    yearBuilt: 1998,
  },
  {
    id: '8',
    title: 'Desert Luxury Retreat',
    location: 'Ahmedabad, Gujarat',
    price: 2400000,
    image: '/properties/townhouse-6.jpg',
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    featured: false,
    description: 'Exclusive desert retreat with resort-style amenities and stunning sunset views.',
    amenities: ['Resort Pool', 'Spa', 'Gym', 'Meditation Garden'],
    images: ['/properties/townhouse-6.jpg'],
    yearBuilt: 2022,
  },
  {
    id: '9',
    title: 'Skyline Signature Apartment',
    location: 'Hyderabad, Telangana',
    price: 2650000,
    image: '/properties/estate-4.jpg',
    bedrooms: 3,
    bathrooms: 3,
    area: 2400,
    featured: true,
    description: 'Premium apartment with skyline-facing living room, smart interiors, and private residents lounge.',
    amenities: ['Clubhouse', 'Infinity Pool', 'Gym', 'Concierge'],
    images: ['/properties/estate-4.jpg'],
    yearBuilt: 2021,
  },
  {
    id: '10',
    title: 'Riverfront Luxe Apartment',
    location: 'Kochi, Kerala',
    price: 2280000,
    image: '/properties/villa-2.jpg',
    bedrooms: 2,
    bathrooms: 2,
    area: 1950,
    featured: true,
    description: 'Modern apartment overlooking the river with high-end finishes and a serene sunset deck.',
    amenities: ['Sky Deck', 'Yoga Studio', 'Business Lounge', '24x7 Security'],
    images: ['/properties/villa-2.jpg'],
    yearBuilt: 2022,
  },
  {
    id: '11',
    title: 'Central Park View Apartment',
    location: 'Noida, Uttar Pradesh',
    price: 2380000,
    image: '/properties/penthouse-3.jpg',
    bedrooms: 3,
    bathrooms: 2,
    area: 2100,
    featured: true,
    description: 'Spacious apartment in a prime central district with landscaped views and premium community amenities.',
    amenities: ['Kids Play Area', 'Indoor Games', 'Party Hall', 'EV Charging'],
    images: ['/properties/penthouse-3.jpg'],
    yearBuilt: 2023,
  },
]
